try:
    print:::("Test du try")
except Exception as e:
    print(f"Erreur : {e}")
finally:
    print("Ã§a passe")    